services:
  postgres:
    build: ./database
    environment:
      POSTGRES_DB: todo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432
  go-api:
    build: ./backend
    ports:
      - 8081:8081
    depends_on:
      - postgres
    links:
      - postgres
  react-app:
    build: ./frontend
    ports:
      - 3000:3000
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3001:3000
    depends_on:
      - prometheus