name: Minimal CI/CD

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          check-latest: true

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          check-latest: true

      - name: Fake build step
        run: |
          echo "Skipping actual build process"
          echo "Workflow completed successfully"