name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # buildint and tests
    - name: Build and test
      run: |
        cd backend && go test ./...
        cd ../frontend && npm install && npm run build

    # Docker-images
    - name: Build Docker images
      run: |
        docker-compose build
        docker tag todo-backend bvbl/todo-backend:latest
        docker tag todo-frontend bvbl/todo-frontend:latest

    # push to Docker Hub
    - name: Push to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker push bvbl/todo-backend:latest
        docker push bvbl/todo-frontend:latest

    # deploy to Kubernetes
    - name: Deploy to Kubernetes
      run: |
        echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > kubeconfig.yaml
        export KUBECONFIG=kubeconfig.yaml
        kubectl apply -f k8s/deployment.yaml
        kubectl get pods  # Проверка, что поды запустились